"""Generate C++ headers for ESP32 firmware from binary assets and game data.

Produces (into firmware/include/generated/):
  - splash_image.h
      16-color indexed splash (palette + 4bpp packed pixels) from
      assets/sprites/splash.png.
  - font_8x16.h / font_6x12.h
      Bitmap fonts with ASCII printable + Cyrillic glyphs, rasterized from a
      TTF (Consolas by default). Symbols are prefixed kFont8x16* / kFont6x12*.
  - sprites_data.h
      RGB565 pixel sheets + 1bpp opacity masks + the SpriteDef table, baked
      from data/sprites.json and the PNG sheets it references.
  - scenes_data.h
      SceneLayer / SceneDef tables baked from data/scenes.json.
  - events_data.h
      ChoiceDef / EventDef tables baked from data/events.json.

The sprite/scene/event tables brace-initialise the structs declared in
firmware/include/game_data_types.h in declared field order — that header is
the contract. Sprites and scenes are referenced by index everywhere; the
indices follow JSON insertion order, so the JSON files are read
order-preserving (the default dict behaviour of json.load).

Requires Pillow:
    pip install Pillow

Usage:
    python scripts/build_firmware_assets.py
    python scripts/build_firmware_assets.py --font-ttf C:/Windows/Fonts/consola.ttf
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.stderr.write(
        "Pillow is required: pip install Pillow\n"
    )
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SPLASH = REPO_ROOT / "assets" / "sprites" / "splash.png"
DEFAULT_DATA_DIR = REPO_ROOT / "data"
DEFAULT_OUT_DIR = REPO_ROOT / "firmware" / "include" / "generated"
DEFAULT_FONT_TTF = Path("C:/Windows/Fonts/consola.ttf")

# Namespace of the structs/sentinels in firmware/include/game_data_types.h.
DATA_NS = "road_east::data"


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def parse_css_color(value: object, context: str) -> int:
    """Convert a CSS hex color ("#rgb" or "#rrggbb") to RGB565."""
    if not isinstance(value, str) or not value.startswith("#"):
        raise SystemExit(f"{context}: expected CSS hex color, got {value!r}.")
    digits = value[1:]
    try:
        if len(digits) == 3:
            r, g, b = (int(d * 2, 16) for d in digits)
        elif len(digits) == 6:
            r, g, b = (int(digits[i : i + 2], 16) for i in (0, 2, 4))
        else:
            raise ValueError(value)
    except ValueError:
        raise SystemExit(f"{context}: malformed CSS hex color {value!r}.") from None
    return rgb_to_565(r, g, b)


def camel_case(name: str) -> str:
    """"walk_forest" -> "WalkForest", for building C++ identifiers."""
    parts = [p for p in re.split(r"[^0-9A-Za-z]+", name) if p]
    if not parts:
        raise SystemExit(f"Cannot derive a C++ identifier from {name!r}.")
    return "".join(p[:1].upper() + p[1:] for p in parts)


def c_string(value: str) -> str:
    """Escape a Python string into a C string literal (UTF-8 passthrough)."""
    out: list[str] = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append(f"\\{ord(ch):03o}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def c_string_or_null(value: object, context: str) -> str:
    if value is None:
        return "nullptr"
    if not isinstance(value, str):
        raise SystemExit(f"{context}: expected a string, got {value!r}.")
    return c_string(value)


def check_i8(value: object, context: str) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or not -128 <= value <= 127:
        raise SystemExit(f"{context}: {value!r} does not fit int8_t.")
    return value


def load_json(path: Path) -> object:
    # json.load builds plain dicts, which preserve key insertion order —
    # that order defines the sprite/scene indices baked below.
    if not path.exists():
        raise SystemExit(f"Data file not found: {path}")
    try:
        with path.open(encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"{path}: invalid JSON: {exc}") from None


def write_header_preamble(
    f, generator_name: str, source: str, extra_includes: tuple[str, ...] = ()
) -> None:
    f.write("// AUTOGENERATED by scripts/build_firmware_assets.py — DO NOT EDIT.\n")
    f.write(f"// Source: {source}\n")
    f.write(f"// Regenerate via: python {generator_name}\n\n")
    f.write("#pragma once\n\n")
    f.write("#include <cstdint>\n")
    for include in extra_includes:
        f.write(f"#include {include}\n")
    f.write("\n")


def build_splash_header(png_path: Path, out_path: Path) -> None:
    img = Image.open(png_path)
    if img.mode != "P":
        raise SystemExit(
            f"{png_path}: expected mode 'P' (indexed), got '{img.mode}'."
        )
    palette = img.getpalette()
    if palette is None:
        raise SystemExit(f"{png_path}: no palette found.")

    # Determine how many palette entries are actually used.
    indices = list(img.tobytes())
    max_index = max(indices)
    if max_index > 15:
        raise SystemExit(
            f"{png_path}: uses {max_index + 1} colors; expected ≤ 16."
        )
    palette_len = 16
    rgb565 = []
    for i in range(palette_len):
        r, g, b = palette[i * 3 : i * 3 + 3]
        rgb565.append(rgb_to_565(r, g, b))

    w, h = img.size
    if w % 2 != 0:
        raise SystemExit(
            f"{png_path}: width must be even for 4bpp packing (got {w})."
        )

    # Pack two indices per byte (high nibble = left pixel).
    packed = bytearray(w * h // 2)
    for y in range(h):
        for x in range(0, w, 2):
            hi = indices[y * w + x] & 0xF
            lo = indices[y * w + x + 1] & 0xF
            packed[(y * w + x) // 2] = (hi << 4) | lo

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        write_header_preamble(
            f, "scripts/build_firmware_assets.py", str(png_path.relative_to(REPO_ROOT))
        )
        f.write("namespace road_east::assets {\n\n")
        f.write(f"constexpr int kSplashWidth = {w};\n")
        f.write(f"constexpr int kSplashHeight = {h};\n\n")
        f.write("// RGB565 palette (16 entries).\n")
        f.write("constexpr uint16_t kSplashPalette[16] = {\n")
        for i, c in enumerate(rgb565):
            sep = "," if i < 15 else ""
            f.write(f"    0x{c:04X}{sep}\n")
        f.write("};\n\n")
        f.write("// 4bpp packed pixel indices, row-major, high nibble = left pixel.\n")
        f.write(f"constexpr uint8_t kSplashPixels[{len(packed)}] = {{\n")
        for i in range(0, len(packed), 16):
            row = packed[i : i + 16]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in row) + ",\n")
        f.write("};\n\n")
        f.write("}  // namespace road_east::assets\n")


# ---------------------------------------------------------------------------
# Fonts
# ---------------------------------------------------------------------------
# Codepoint ranges baked into the fonts:
#   0x20..0x7E  printable ASCII   (indices 0..94)
#   0x401       Ё                 (index 95)
#   0x410..0x44F А..я             (indices 96..159)
#   0x451       ё                 (index 160)
#   FONT_EXTRA  punctuation       (indices 161..)
#
# glyphIndex() in firmware/src/common/text_render.cpp mirrors this layout —
# keep the two in sync, and only ever append, so existing indices stay put.
# Typographic punctuation that Russian copy actually uses; without it the
# renderer silently substitutes a space.
FONT_EXTRA: list[int] = [
    0x00AB,  # «
    0x00BB,  # »
    0x2013,  # –
    0x2014,  # —
    0x2018,  # ‘
    0x2019,  # ’
    0x201C,  # “
    0x201D,  # ”
    0x2026,  # …
]

FONT_CODEPOINTS: list[int] = (
    list(range(0x20, 0x7F))
    + [0x401]
    + list(range(0x410, 0x450))
    + [0x451]
    + FONT_EXTRA
)


def rasterize_glyph(
    font: ImageFont.FreeTypeFont,
    cp: int,
    glyph_w: int,
    glyph_h: int,
    x_off: int,
    y_off: int,
) -> bytes:
    """Render one glyph into a glyph_w x glyph_h 1-bit bitmap.

    One byte per pixel row, MSB = leftmost pixel, glyph_h bytes per glyph.
    """
    img = Image.new("1", (glyph_w, glyph_h), 0)
    draw = ImageDraw.Draw(img)
    draw.text((x_off, y_off), chr(cp), font=font, fill=1)
    rows = bytearray(glyph_h)
    px = img.load()
    for y in range(glyph_h):
        b = 0
        for x in range(glyph_w):
            if px[x, y]:
                b |= 1 << (7 - x)
        rows[y] = b
    return bytes(rows)


def build_font_header(
    ttf_path: Path,
    out_path: Path,
    name: str,
    glyph_w: int,
    glyph_h: int,
    advance: int,
    font_size: int,
    x_off: int,
    y_off: int,
) -> None:
    """Rasterize FONT_CODEPOINTS into a glyph_w x glyph_h bitmap table.

    `advance` is the per-character cursor step and may be smaller than
    `glyph_w`: a handful of Cyrillic letters (ы, ю, щ) and '0' need one extra
    column of ink, and cutting the cell down to the advance clips them into a
    different letter. Letting them bleed into the neighbouring cell is the
    lesser evil — glyphs are drawn with a transparent background, so they
    merely touch.
    """
    if not ttf_path.exists():
        raise SystemExit(f"Font not found: {ttf_path}")
    if glyph_w > 8:
        raise SystemExit(
            f"font {name}: glyph width {glyph_w} breaks the one-byte-per-row encoding."
        )

    font = ImageFont.truetype(str(ttf_path), font_size)

    # Guard against silent clipping: a glyph whose ink is wider than the cell
    # renders as a different character, which is worse than a build failure.
    clipped = []
    for cp in FONT_CODEPOINTS:
        probe = Image.new("1", (glyph_w + 8, glyph_h + 8), 0)
        ImageDraw.Draw(probe).text((x_off, y_off), chr(cp), font=font, fill=1)
        box = probe.getbbox()
        if box is not None and (box[2] > glyph_w or box[3] > glyph_h):
            clipped.append(f"U+{cp:04X} {chr(cp)!r} ({box[2]}x{box[3]})")
    if clipped:
        raise SystemExit(
            f"font {name}: {len(clipped)} glyph(s) do not fit the {glyph_w}x{glyph_h} "
            f"cell at size {font_size}: {', '.join(clipped[:12])}"
        )

    glyph_data = bytearray()
    for cp in FONT_CODEPOINTS:
        glyph_data.extend(rasterize_glyph(font, cp, glyph_w, glyph_h, x_off, y_off))

    prefix = f"kFont{name}"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        write_header_preamble(
            f, "scripts/build_firmware_assets.py", str(ttf_path)
        )
        f.write("namespace road_east::assets {\n\n")
        f.write(f"inline constexpr int {prefix}GlyphWidth = {glyph_w};\n")
        f.write(f"inline constexpr int {prefix}GlyphHeight = {glyph_h};\n")
        f.write(
            f"// Cursor step per character; may be < GlyphWidth, see the generator.\n"
        )
        f.write(f"inline constexpr int {prefix}GlyphAdvance = {advance};\n")
        f.write(f"inline constexpr int {prefix}GlyphCount = {len(FONT_CODEPOINTS)};\n\n")
        f.write(
            f"// Bitmap rows, MSB-first per row. {glyph_h} bytes per glyph, in the order\n"
            "// produced by the codepoint mapping in the .cpp companion.\n"
        )
        total = len(glyph_data)
        f.write(f"inline constexpr uint8_t {prefix}Glyphs[{total}] = {{\n")
        for i in range(0, total, glyph_h):
            row = glyph_data[i : i + glyph_h]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in row))
            f.write(f",  // cp 0x{FONT_CODEPOINTS[i // glyph_h]:04X}\n")
        f.write("};\n\n")
        f.write("}  // namespace road_east::assets\n")


# ---------------------------------------------------------------------------
# Sprites (data/sprites.json + assets/sprites/*.png)
# ---------------------------------------------------------------------------
def build_sprites_header(sprites_doc: dict, out_path: Path) -> dict[str, int]:
    """Bake sprite sheets into RGB565 + 1bpp mask tables.

    Returns {sprite name: index into kSprites} for the scene generator.
    """
    sprites = sprites_doc.get("sprites")
    if not isinstance(sprites, dict) or not sprites:
        raise SystemExit("sprites.json: missing or empty 'sprites' object.")
    sprite_index = {name: i for i, name in enumerate(sprites)}

    entries: list[tuple[str, str, int, int, int, int, int, int, list[int], bytearray]] = []
    for name, spec in sprites.items():
        ctx = f"sprites.json: sprite '{name}'"
        try:
            src = REPO_ROOT / spec["src"]
            frame_w = int(spec["frameWidth"])
            frame_h = int(spec["frameHeight"])
            frames = int(spec["frames"])
            fps = int(spec["fps"])
        except (KeyError, TypeError, ValueError) as exc:
            raise SystemExit(f"{ctx}: bad or missing field ({exc!r}).") from None
        if frames < 1 or frame_w < 1 or frame_h < 1:
            raise SystemExit(f"{ctx}: frameWidth/frameHeight/frames must be >= 1.")
        if not src.exists():
            raise SystemExit(f"{ctx}: sheet not found: {src}")

        sheet_w = frame_w * frames
        img = Image.open(src).convert("RGBA")
        if img.size != (sheet_w, frame_h):
            raise SystemExit(
                f"{ctx}: {src.name} is {img.size[0]}x{img.size[1]}, expected "
                f"frameWidth*frames x frameHeight = {sheet_w}x{frame_h}."
            )

        px = img.load()
        row_bytes = (sheet_w + 7) // 8
        pixels: list[int] = []
        mask = bytearray(row_bytes * frame_h)
        for y in range(frame_h):
            for x in range(sheet_w):
                r, g, b, a = px[x, y]
                if a >= 128:
                    pixels.append(rgb_to_565(r, g, b))
                    mask[y * row_bytes + x // 8] |= 1 << (7 - x % 8)
                else:
                    pixels.append(0x0000)
        entries.append(
            (name, camel_case(name), frame_w, frame_h, frames, fps, sheet_w,
             row_bytes, pixels, mask)
        )

    transport = sprites_doc.get("transport_default")
    if not isinstance(transport, list) or not transport:
        raise SystemExit("sprites.json: missing or empty 'transport_default' array.")
    for t in transport:
        if t not in sprite_index:
            raise SystemExit(f"sprites.json: transport_default names unknown sprite {t!r}.")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        write_header_preamble(
            f, "scripts/build_firmware_assets.py",
            "data/sprites.json + assets/sprites/*.png",
            ('"game_data_types.h"',),
        )
        f.write("namespace road_east::assets {\n\n")
        for (name, camel, frame_w, frame_h, frames, fps, sheet_w,
             row_bytes, pixels, mask) in entries:
            f.write(f"// {name}: {frames} frame(s) of {frame_w}x{frame_h}, sheet {sheet_w}x{frame_h}.\n")
            f.write("// RGB565, row-major, sheetWidth * frameHeight; 0x0000 where the mask bit is clear.\n")
            f.write(f"inline constexpr uint16_t kSprite{camel}Pixels[{len(pixels)}] = {{\n")
            for i in range(0, len(pixels), 12):
                chunk = pixels[i : i + 12]
                f.write("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",\n")
            f.write("};\n\n")
            f.write(f"// 1bpp opacity mask, MSB-first, {row_bytes} byte(s) per row; bit set = opaque.\n")
            f.write(f"inline constexpr uint8_t kSprite{camel}Mask[{len(mask)}] = {{\n")
            for i in range(0, len(mask), 16):
                chunk = mask[i : i + 16]
                f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
            f.write("};\n\n")

        f.write(f"inline constexpr int kSpriteCount = {len(entries)};\n\n")
        f.write("// Order matches data/sprites.json \"sprites\" — indices are the contract.\n")
        f.write(f"inline constexpr {DATA_NS}::SpriteDef kSprites[kSpriteCount] = {{\n")
        f.write("    // name, frameWidth, frameHeight, frames, fps, sheetWidth, pixels, mask\n")
        for (name, camel, frame_w, frame_h, frames, fps, sheet_w, *_rest) in entries:
            f.write(
                f"    {{ {c_string(name)}, {frame_w}, {frame_h}, {frames}, {fps}, "
                f"{sheet_w}, kSprite{camel}Pixels, kSprite{camel}Mask }},\n"
            )
        f.write("};\n\n")
        f.write("// Indices into kSprites for data/sprites.json \"transport_default\".\n")
        f.write(f"inline constexpr int kTransportSpriteCount = {len(transport)};\n")
        values = ", ".join(str(sprite_index[t]) for t in transport)
        names = ", ".join(transport)
        f.write(
            f"inline constexpr int8_t kTransportSprites[kTransportSpriteCount] = "
            f"{{ {values} }};  // {names}\n\n"
        )
        f.write("}  // namespace road_east::assets\n")
    return sprite_index


# ---------------------------------------------------------------------------
# Scenes (data/scenes.json)
# ---------------------------------------------------------------------------
ANCHOR_MAP = {
    "top-left": "SpriteAnchor::TopLeft",
    "center-bottom": "SpriteAnchor::CenterBottom",
    "left-bottom": "SpriteAnchor::LeftBottom",
}


def scene_layer_initializer(layer: dict, sprite_index: dict[str, int], ctx: str) -> str:
    """One SceneLayer brace-initialiser, all fields in declared order."""
    ltype = layer.get("type")
    if ltype == "rect":
        type_v = f"{DATA_NS}::LayerType::Rect"
        color = parse_css_color(layer["color"], ctx) if "color" in layer else 0
        # Sprite fields: harmless defaults for rect layers.
        sprite_v = f"{DATA_NS}::kSpriteHero"
        anchor_v = f"{DATA_NS}::SpriteAnchor::TopLeft"
        tile_v = "false"
        scroll = 0
        spacing = 0
        animated_v = "true"
        freeze = -1
    elif ltype == "sprite":
        type_v = f"{DATA_NS}::LayerType::Sprite"
        color = 0  # Rect-only field; harmless default for sprite layers.
        sprite_name = layer.get("sprite")
        if sprite_name == "${hero}":
            sprite_v = f"{DATA_NS}::kSpriteHero"
        elif sprite_name in sprite_index:
            sprite_v = f"{sprite_index[sprite_name]} /*{sprite_name}*/"
        else:
            raise SystemExit(f"{ctx}: unknown sprite {sprite_name!r}.")
        anchor_name = layer.get("anchor", "top-left")
        if anchor_name not in ANCHOR_MAP:
            raise SystemExit(f"{ctx}: unknown anchor {anchor_name!r}.")
        anchor_v = f"{DATA_NS}::{ANCHOR_MAP[anchor_name]}"
        tile_v = "true" if layer.get("tile", False) else "false"
        scroll = int(layer.get("scrollSpeed", 0))
        spacing = int(layer.get("spacing", 0))
        # SceneLayer stores animationSpeed as a bool, which is all the PWA
        # content uses. Refuse anything else rather than silently rounding a
        # half-speed layer up to full speed.
        anim_speed = layer.get("animationSpeed", 1)
        if anim_speed not in (0, 1):
            raise SystemExit(
                f"{ctx}: animationSpeed={anim_speed!r} is not representable — "
                "SceneLayer.animated is a flag; widen it to fixed-point first."
            )
        animated_v = "true" if anim_speed else "false"
        freeze = check_i8(layer.get("freezeFrame", -1), f"{ctx}: freezeFrame")
    else:
        raise SystemExit(f"{ctx}: unknown layer type {ltype!r}.")

    x = int(layer.get("x", 0))
    y = int(layer.get("y", 0))
    w = int(layer.get("w", 0))
    h = int(layer.get("h", 0))
    return (
        f"{{ {type_v}, {x}, {y}, {w}, {h}, 0x{color:04X}, "
        f"{sprite_v}, {anchor_v}, {tile_v}, {scroll}, {spacing}, {animated_v}, {freeze} }}"
    )


def build_scenes_header(
    scenes_doc: dict, sprite_index: dict[str, int], out_path: Path
) -> dict[str, int]:
    """Bake scene layer tables. Returns {scene id: index into kScenes}."""
    scenes = scenes_doc.get("scenes")
    if not isinstance(scenes, dict) or not scenes:
        raise SystemExit("scenes.json: missing or empty 'scenes' object.")
    scene_index = {name: i for i, name in enumerate(scenes)}

    default_scene = scenes_doc.get("default_scene")
    if default_scene not in scene_index:
        raise SystemExit(f"scenes.json: default_scene {default_scene!r} is not a scene.")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        write_header_preamble(
            f, "scripts/build_firmware_assets.py", "data/scenes.json",
            ('"game_data_types.h"',),
        )
        f.write("namespace road_east::assets {\n\n")
        f.write(f"// Layer fields, in {DATA_NS}::SceneLayer order:\n")
        f.write("//   type, x, y, w, h, color, sprite, anchor, tile, scrollSpeed, spacing, animated, freezeFrame\n\n")
        for name, spec in scenes.items():
            ctx = f"scenes.json: scene '{name}'"
            layers = spec.get("layers")
            if not isinstance(layers, list) or not layers:
                raise SystemExit(f"{ctx}: missing or empty 'layers'.")
            camel = camel_case(name)
            f.write(f"inline constexpr {DATA_NS}::SceneLayer kScene{camel}Layers[{len(layers)}] = {{\n")
            for i, layer in enumerate(layers):
                init = scene_layer_initializer(layer, sprite_index, f"{ctx} layer {i}")
                f.write(f"    {init},\n")
            f.write("};\n\n")

        f.write(f"inline constexpr int kSceneCount = {len(scenes)};\n\n")
        f.write("// Order matches data/scenes.json \"scenes\" — indices are the contract.\n")
        f.write(f"inline constexpr {DATA_NS}::SceneDef kScenes[kSceneCount] = {{\n")
        f.write("    // id, background, layers, layerCount\n")
        for name, spec in scenes.items():
            if "background" not in spec:
                raise SystemExit(f"scenes.json: scene '{name}': missing 'background'.")
            bg = parse_css_color(spec["background"], f"scenes.json: scene '{name}' background")
            camel = camel_case(name)
            f.write(f"    {{ {c_string(name)}, 0x{bg:04X}, kScene{camel}Layers, {len(spec['layers'])} }},\n")
        f.write("};\n\n")
        f.write(
            f"inline constexpr int8_t kDefaultSceneIndex = {scene_index[default_scene]};"
            f"  // {default_scene}\n\n"
        )
        f.write("}  // namespace road_east::assets\n")
    return scene_index


# ---------------------------------------------------------------------------
# Events (data/events.json)
# ---------------------------------------------------------------------------
def scene_index_expr(name: object, scene_index: dict[str, int], ctx: str) -> str:
    if name not in scene_index:
        raise SystemExit(f"{ctx}: unknown scene {name!r}.")
    return f"{scene_index[name]} /*{name}*/"


def build_events_header(
    events_doc: object, scene_index: dict[str, int], out_path: Path
) -> None:
    if not isinstance(events_doc, list) or not events_doc:
        raise SystemExit("events.json: expected a non-empty array of events.")

    event_ids: set[str] = set()
    for event in events_doc:
        eid = event.get("id") if isinstance(event, dict) else None
        if not isinstance(eid, str) or not eid:
            raise SystemExit(f"events.json: event without a valid 'id': {event!r}.")
        if eid in event_ids:
            raise SystemExit(f"events.json: duplicate event id {eid!r}.")
        event_ids.add(eid)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        write_header_preamble(
            f, "scripts/build_firmware_assets.py", "data/events.json",
            ('"game_data_types.h"',),
        )
        f.write("namespace road_east::assets {\n\n")
        for event in events_doc:
            eid = event["id"]
            ctx = f"events.json: event '{eid}'"
            choices = event.get("choices")
            if not isinstance(choices, list) or not choices:
                raise SystemExit(f"{ctx}: missing or empty 'choices'.")
            camel = camel_case(eid)
            f.write(f"inline constexpr {DATA_NS}::ChoiceDef kEvent{camel}Choices[{len(choices)}] = {{\n")
            for i, choice in enumerate(choices):
                cctx = f"{ctx} choice {i}"
                action = choice.get("action")
                if not isinstance(action, str) or not action:
                    raise SystemExit(f"{cctx}: missing 'action'.")
                next_id = choice.get("next_id")
                if next_id not in event_ids:
                    raise SystemExit(f"{cctx}: next_id {next_id!r} is not an event id.")
                # Three-way "scene": absent = inherit, null = none, name = index.
                if "scene" not in choice:
                    scene_expr = f"{DATA_NS}::kSceneInherit"
                elif choice["scene"] is None:
                    scene_expr = f"{DATA_NS}::kSceneNone"
                else:
                    scene_expr = scene_index_expr(choice["scene"], scene_index, cctx)
                if choice.get("result_scene") is None:
                    result_scene_expr = f"{DATA_NS}::kSceneNone"
                else:
                    result_scene_expr = scene_index_expr(
                        choice["result_scene"], scene_index, f"{cctx} result_scene"
                    )
                if choice.get("transport_mod") is None:
                    transport_expr = f"{DATA_NS}::kTransportKeep"
                else:
                    transport_expr = str(check_i8(choice["transport_mod"], f"{cctx}: transport_mod"))
                food = check_i8(choice.get("food_mod", 0), f"{cctx}: food_mod")
                hp = check_i8(choice.get("hp_mod", 0), f"{cctx}: hp_mod")
                mood = check_i8(choice.get("mood_mod", 0), f"{cctx}: mood_mod")
                f.write("    {\n")
                f.write(f"        /*action=*/{c_string(action)},\n")
                f.write(
                    f"        /*transportMod=*/{transport_expr}, /*foodMod=*/{food}, "
                    f"/*hpMod=*/{hp}, /*moodMod=*/{mood},\n"
                )
                f.write(f"        /*nextId=*/{c_string(next_id)},\n")
                f.write(f"        /*scene=*/{scene_expr},\n")
                f.write(f"        /*resultTitle=*/{c_string_or_null(choice.get('result_title'), cctx)},\n")
                f.write(f"        /*resultText=*/{c_string_or_null(choice.get('result_text'), cctx)},\n")
                f.write(f"        /*resultScene=*/{result_scene_expr},\n")
                f.write(f"        /*continueText=*/{c_string_or_null(choice.get('continue_text'), cctx)},\n")
                f.write("    },\n")
            f.write("};\n\n")

        f.write(f"inline constexpr int kEventCount = {len(events_doc)};\n\n")
        f.write("// Order matches data/events.json. next_id is resolved by id at runtime.\n")
        f.write(f"inline constexpr {DATA_NS}::EventDef kEvents[kEventCount] = {{\n")
        for event in events_doc:
            eid = event["id"]
            ctx = f"events.json: event '{eid}'"
            text = event.get("text")
            if not isinstance(text, str) or not text:
                raise SystemExit(f"{ctx}: missing 'text'.")
            if event.get("scene") is None:
                scene_expr = f"{DATA_NS}::kSceneNone"
            else:
                scene_expr = scene_index_expr(event["scene"], scene_index, ctx)
            fuel = check_i8(event.get("fuel_mod", 0), f"{ctx}: fuel_mod")
            camel = camel_case(eid)
            f.write("    {\n")
            f.write(f"        /*id=*/{c_string(eid)},\n")
            f.write(f"        /*text=*/{c_string(text)},\n")
            f.write(f"        /*hint=*/{c_string_or_null(event.get('hint'), ctx)},\n")
            f.write(f"        /*scene=*/{scene_expr},\n")
            f.write(
                f"        /*unlockFriend=*/{c_string_or_null(event.get('unlock_friend'), ctx)}, "
                f"/*unlockFriend2=*/{c_string_or_null(event.get('unlock_friend_2'), ctx)},\n"
            )
            f.write(f"        /*fuelMod=*/{fuel},\n")
            f.write(f"        /*choices=*/kEvent{camel}Choices, /*choiceCount=*/{len(event['choices'])},\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write("}  // namespace road_east::assets\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--splash-png", type=Path, default=DEFAULT_SPLASH)
    parser.add_argument("--font-ttf", type=Path, default=DEFAULT_FONT_TTF)
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args()

    splash_out = args.out_dir / "splash_image.h"
    font16_out = args.out_dir / "font_8x16.h"
    font12_out = args.out_dir / "font_6x12.h"
    sprites_out = args.out_dir / "sprites_data.h"
    scenes_out = args.out_dir / "scenes_data.h"
    events_out = args.out_dir / "events_data.h"

    print(f"splash:  {args.splash_png} -> {splash_out}")
    build_splash_header(args.splash_png, splash_out)
    print(f"font:    {args.font_ttf} -> {font16_out}")
    build_font_header(args.font_ttf, font16_out, "8x16",
                      glyph_w=8, glyph_h=16, advance=8,
                      font_size=13, x_off=0, y_off=1)
    print(f"font:    {args.font_ttf} -> {font12_out}")
    # 7px cells stepped 6px apart. Size 11 rather than 12: at 12 some 28 glyphs
    # ('0', ы, ю, щ, Ж …) need the 7th column and visibly collide with the next
    # letter, at 11 only five do (Y g Ж ж м) and they merely touch.
    build_font_header(args.font_ttf, font12_out, "6x12",
                      glyph_w=7, glyph_h=12, advance=6,
                      font_size=11, x_off=0, y_off=0)

    sprites_doc = load_json(args.data_dir / "sprites.json")
    scenes_doc = load_json(args.data_dir / "scenes.json")
    events_doc = load_json(args.data_dir / "events.json")

    print(f"sprites: {args.data_dir / 'sprites.json'} -> {sprites_out}")
    sprite_index = build_sprites_header(sprites_doc, sprites_out)
    print(f"scenes:  {args.data_dir / 'scenes.json'} -> {scenes_out}")
    scene_index = build_scenes_header(scenes_doc, sprite_index, scenes_out)
    print(f"events:  {args.data_dir / 'events.json'} -> {events_out}")
    build_events_header(events_doc, scene_index, events_out)
    print("done.")


if __name__ == "__main__":
    main()
