"""Generate C++ headers for ESP32 firmware from binary assets.

Currently produces:
  - firmware/include/generated/splash_image.h
      16-color indexed splash (palette + 4bpp packed pixels) from
      assets/sprites/splash.png.
  - firmware/include/generated/font_8x16.h
      8x16 bitmap font with ASCII printable + Cyrillic glyphs, rasterized
      from a TTF (Consolas by default).

Requires Pillow:
    pip install Pillow

Usage:
    python scripts/build_firmware_assets.py
    python scripts/build_firmware_assets.py --font-ttf C:/Windows/Fonts/consola.ttf
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.stderr.write(
        "Pillow is required: pip install Pillow\n"
    )
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SPLASH = REPO_ROOT / "assets" / "sprites" / "splash.png"
DEFAULT_OUT_DIR = REPO_ROOT / "firmware" / "include" / "generated"
DEFAULT_FONT_TTF = Path("C:/Windows/Fonts/consola.ttf")


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def write_header_preamble(f, generator_name: str, source: str) -> None:
    f.write("// AUTOGENERATED by scripts/build_firmware_assets.py — DO NOT EDIT.\n")
    f.write(f"// Source: {source}\n")
    f.write(f"// Regenerate via: python {generator_name}\n\n")
    f.write("#pragma once\n\n")
    f.write("#include <cstdint>\n\n")


def build_splash_header(png_path: Path, out_path: Path) -> None:
    img = Image.open(png_path)
    if img.mode != "P":
        raise SystemExit(
            f"{png_path}: expected mode 'P' (indexed), got '{img.mode}'."
        )
    palette = img.getpalette()
    if palette is None:
        raise SystemExit(f"{png_path}: no palette found.")

    # Determine how many palette entries are actually used.
    indices = list(img.tobytes())
    max_index = max(indices)
    if max_index > 15:
        raise SystemExit(
            f"{png_path}: uses {max_index + 1} colors; expected ≤ 16."
        )
    palette_len = 16
    rgb565 = []
    for i in range(palette_len):
        r, g, b = palette[i * 3 : i * 3 + 3]
        rgb565.append(rgb_to_565(r, g, b))

    w, h = img.size
    if w % 2 != 0:
        raise SystemExit(
            f"{png_path}: width must be even for 4bpp packing (got {w})."
        )

    # Pack two indices per byte (high nibble = left pixel).
    packed = bytearray(w * h // 2)
    for y in range(h):
        for x in range(0, w, 2):
            hi = indices[y * w + x] & 0xF
            lo = indices[y * w + x + 1] & 0xF
            packed[(y * w + x) // 2] = (hi << 4) | lo

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        write_header_preamble(
            f, "scripts/build_firmware_assets.py", str(png_path.relative_to(REPO_ROOT))
        )
        f.write("namespace road_east::assets {\n\n")
        f.write(f"constexpr int kSplashWidth = {w};\n")
        f.write(f"constexpr int kSplashHeight = {h};\n\n")
        f.write("// RGB565 palette (16 entries).\n")
        f.write("constexpr uint16_t kSplashPalette[16] = {\n")
        for i, c in enumerate(rgb565):
            sep = "," if i < 15 else ""
            f.write(f"    0x{c:04X}{sep}\n")
        f.write("};\n\n")
        f.write("// 4bpp packed pixel indices, row-major, high nibble = left pixel.\n")
        f.write(f"constexpr uint8_t kSplashPixels[{len(packed)}] = {{\n")
        for i in range(0, len(packed), 16):
            row = packed[i : i + 16]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in row) + ",\n")
        f.write("};\n\n")
        f.write("}  // namespace road_east::assets\n")


# Codepoint ranges baked into the font:
#   0x20..0x7E  printable ASCII   (indices 0..94)
#   0x401       Ё                 (index 95)
#   0x410..0x44F А..я             (indices 96..159)
#   0x451       ё                 (index 160)
FONT_CODEPOINTS: list[int] = (
    list(range(0x20, 0x7F))
    + [0x401]
    + list(range(0x410, 0x450))
    + [0x451]
)
FONT_GLYPH_W = 8
FONT_GLYPH_H = 16


def rasterize_glyph(font: ImageFont.FreeTypeFont, cp: int, x_off: int, y_off: int) -> bytes:
    """Render one glyph into an 8x16 1-bit bitmap, packed MSB-first per row."""
    img = Image.new("1", (FONT_GLYPH_W, FONT_GLYPH_H), 0)
    draw = ImageDraw.Draw(img)
    draw.text((x_off, y_off), chr(cp), font=font, fill=1)
    rows = bytearray(FONT_GLYPH_H)
    px = img.load()
    for y in range(FONT_GLYPH_H):
        b = 0
        for x in range(FONT_GLYPH_W):
            if px[x, y]:
                b |= 1 << (7 - x)
        rows[y] = b
    return bytes(rows)


def build_font_header(ttf_path: Path, out_path: Path) -> None:
    if not ttf_path.exists():
        raise SystemExit(f"Font not found: {ttf_path}")
    # Size 13 with a small y-offset fits a clean 8x16 cell for Consolas.
    font = ImageFont.truetype(str(ttf_path), 13)
    x_off, y_off = 0, 1

    glyph_data = bytearray()
    for cp in FONT_CODEPOINTS:
        glyph_data.extend(rasterize_glyph(font, cp, x_off, y_off))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        write_header_preamble(
            f, "scripts/build_firmware_assets.py", str(ttf_path)
        )
        f.write("namespace road_east::assets {\n\n")
        f.write(f"constexpr int kFontGlyphWidth = {FONT_GLYPH_W};\n")
        f.write(f"constexpr int kFontGlyphHeight = {FONT_GLYPH_H};\n")
        f.write(f"constexpr int kFontGlyphCount = {len(FONT_CODEPOINTS)};\n\n")
        f.write(
            "// Bitmap rows, MSB-first per row. 16 bytes per glyph, in the order\n"
            "// produced by the codepoint mapping in the .cpp companion.\n"
        )
        total = len(glyph_data)
        f.write(f"constexpr uint8_t kFontGlyphs[{total}] = {{\n")
        for i in range(0, total, FONT_GLYPH_H):
            row = glyph_data[i : i + FONT_GLYPH_H]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in row))
            f.write(f",  // cp 0x{FONT_CODEPOINTS[i // FONT_GLYPH_H]:04X}\n")
        f.write("};\n\n")
        f.write("}  // namespace road_east::assets\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--splash-png", type=Path, default=DEFAULT_SPLASH)
    parser.add_argument("--font-ttf", type=Path, default=DEFAULT_FONT_TTF)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args()

    splash_out = args.out_dir / "splash_image.h"
    font_out = args.out_dir / "font_8x16.h"

    print(f"splash: {args.splash_png} -> {splash_out}")
    build_splash_header(args.splash_png, splash_out)
    print(f"font:   {args.font_ttf} -> {font_out}")
    build_font_header(args.font_ttf, font_out)
    print("done.")


if __name__ == "__main__":
    main()
